env:
    githubEmail: pablo.anttila@gmail.com
    deployToRepo: papplo.github.io

name: Github Pages Astro CI

on: 
    push:
      branches: [main]
    pull_request:
      branches: [main]
    
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/chechout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          touch ./dist/.nojekyll

      - name: Push Pages to repo
        uses: cpina/github-actions-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: ${{ github.actor }}
          destination-repository-name: ${{ env.deployToRepo }}
          user-email: ${{ env.githubEmail }}
          commit-message: Deploy ORIGIN_COMMIT
          target-branch: feature/cd-github-pages
